name: Copy File to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Copy a specific file to the server
     # - name: Copy file via SCP
      #  uses: appleboy/scp-action@master
      #  with:
       #   host: ${{ secrets.HOST }}
        #  username: ${{ secrets.UNAME }}
         # port: ${{ secrets.PORT }}
         # key: ${{ secrets.TEST_PRIVATE }}
         # source: "."
         # target: "/home/ubuntu/test"
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.UNAME }}
          key: ${{ secrets.TEST_PRIVATE }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
