on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Copy file via SCP
        uses: appleboy/scp-action@master
        with:
          source: "."
          target: "/home/tayab/test-ci-cd"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.UNAME }}
          key: ${{ secrets.TEST_PRIVATE }}
          port: ${{ secrets.PORT }}

     
      - name: Run server tasks
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.UNAME }}
          key: ${{ secrets.TEST_PRIVATE }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
